name: build

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!trunk'
    tags-ignore:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: docker/setup-buildx-action@v1

      # See https://gitlab.alpinelinux.org/alpine/aports/-/issues/12406
      - run: docker run --rm --privileged linuxkit/binfmt:v0.8

      - uses: docker/build-push-action@v2.7.0
        with:
          build-args: --progress plain
          platforms: linux/amd64,linux/arm64
